# Python-related configuration of the project.

[tool.isort]
profile = "black"

[tool.pylint."MESSAGES CONTROL"]
disable = [
    'C0103',  # Module name doesn't conform to snake_case naming style
    'R0903',  # (too-few-public-methods) Too few public methods (1/2)
    'R0913',  # (too-many-arguments) Too many arguments (7/5)
    'R0914',  # (too-many-locals) Too many local variables (16/15)
    'R0902',  # (too-many-instance-attributes) Too many instance attributes (10/7)
]

[tool.pylint.format]
expected-line-ending-format = "LF"
