# Python-related configuration of the project.

[tool.isort]
profile = "black"

[tool.pylint."MESSAGES CONTROL"]
disable = [
    "C0103",
    "C0121",
    "C0330",
    "C0412",
    "E0401",
    "R0801",
    "R0903",
    "R0913",
    "R0914",
    "W0603",
    "W1203",
]

[tool.pylint.format]
expected-line-ending-format = "LF"
